name: "SpicyDiff 🌶️"
description: "LLM-powered code review with personality — ROAST or PRAISE your PRs! Supports OpenAI, DeepSeek, and more."
author: "SpicyDiff Team"

branding:
  icon: "message-circle"
  color: "red"

inputs:
  github-token:
    description: "GitHub token with pull-request write permission"
    required: true
  api-key:
    description: "API key for the LLM provider"
    required: true
  provider:
    description: "LLM provider shortcut: openai, deepseek, qwen, doubao, zhipu, moonshot, gemini, yi, baichuan, minimax"
    required: false
    default: ""
  model:
    description: "LLM model name (optional — each provider has a sensible default)"
    required: false
    default: ""
  mode:
    description: "Review personality — ROAST (brutally honest), PRAISE (blindly optimistic), or SECURITY (paranoid auditor)"
    required: false
    default: "ROAST"
  language:
    description: "Output language: zh (中文) or en (English)"
    required: false
    default: "en"
  base-url:
    description: "Custom base URL for any OpenAI-compatible API (overrides provider preset)"
    required: false
    default: ""
  temperature:
    description: "LLM sampling temperature (0.0 = deterministic, 1.0 = creative). Default: 0.7"
    required: false
    default: "0.7"
  max-tokens:
    description: "Maximum tokens in the LLM response. Default: 4096"
    required: false
    default: "4096"
  max-diff-chars:
    description: "Maximum diff size (chars) sent to the LLM. Larger diffs are truncated. Default: 60000"
    required: false
    default: "60000"
  exclude-patterns:
    description: "Comma-separated glob patterns to exclude from review (e.g. '*.test.js,docs/**')"
    required: false
    default: ""
  pr-number:
    description: "Pull Request number (auto-detected from event context; set manually for workflow_dispatch)"
    required: false
    default: ""
  custom-rules:
    description: "Comma-separated custom review rules to enforce (e.g. 'No hardcoded URLs,All functions must have docstrings')"
    required: false
    default: ""
  dry-run:
    description: "If true, prints the review to logs without posting to GitHub. Default: false"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_API_KEY: ${{ inputs.api-key }}
    INPUT_PROVIDER: ${{ inputs.provider }}
    INPUT_MODEL: ${{ inputs.model }}
    INPUT_MODE: ${{ inputs.mode }}
    INPUT_LANGUAGE: ${{ inputs.language }}
    INPUT_BASE_URL: ${{ inputs.base-url }}
    INPUT_TEMPERATURE: ${{ inputs.temperature }}
    INPUT_MAX_TOKENS: ${{ inputs.max-tokens }}
    INPUT_MAX_DIFF_CHARS: ${{ inputs.max-diff-chars }}
    INPUT_EXCLUDE_PATTERNS: ${{ inputs.exclude-patterns }}
    INPUT_PR_NUMBER: ${{ inputs.pr-number }}
    INPUT_CUSTOM_RULES: ${{ inputs.custom-rules }}
    INPUT_DRY_RUN: ${{ inputs.dry-run }}
